name: Build Flutter Apps

on:
  push:
    branches:
      - main
    paths:
      - 'client-app/**'
      - 'partner-app/**'
      - '.github/workflows/deploy-flutter.yml'

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          channel: 'stable'

      - name: Client App - Get Dependencies
        working-directory: ./client-app
        run: flutter pub get

      - name: Client App - Build APK
        working-directory: ./client-app
        run: flutter build apk --release

      - name: Upload Client APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-app-apk
          path: client-app/build/app/outputs/flutter-apk/app-release.apk

  build-partner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'
          channel: 'stable'

      - name: Partner App - Get Dependencies
        working-directory: ./partner-app
        run: flutter pub get

      - name: Partner App - Build APK
        working-directory: ./partner-app
        run: flutter build apk --release

      - name: Upload Partner APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: partner-app-apk
          path: partner-app/build/app/outputs/flutter-apk/app-release.apk
